#!/usr/bin/env bash

# Bash, git completion and color
if [ -f $(brew --prefix)/etc/bash_completion ]; then
    . $(brew --prefix)/etc/bash_completion
    . $(brew --prefix)/etc/bash_completion.d/git-completion.bash
    . $(brew --prefix)/etc/bash_completion.d/git-prompt.sh
    . $(brew --prefix)/etc/bash_completion.d/bazel-complete.bash
fi
GIT_PS1_SHOWDIRTYSTATE=true
