#!/usr/bin/env bash

# $PATH is left-associative; utilities sourced first take precedence.
#
# e.g. here we force Brew-installed `curl` to override the system `curl`
# but we don't allow non-prefixed GNU Coreutils to override default
# system utilities.

if [[ "$(uname -s)" == "Darwin" ]]; then
    export PATH="$HOME/bin:/opt/local/bin:/opt/local/sbin:$PATH"
elif [[ "$(uname -s)" == "Linux" ]]; then
    #TODO
fi
