#!/usr/bin/env bash

case "$TERM" in
    xterm-color) color_prompt=yes;;
esac

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\w\[\033[01;33m\]$(__git_ps1)\[\033[01;34m\] \$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\[\033[01;33m\]$(__git_ps1)\[\033[01;34m\] \$\[\033[00m\] '
fi
unset color_prompt force_color_prompt
